import { v4 as uuidv4 } from "uuid";
import { getAdapter } from "../driver.js";
import { parseJson, stringifyJson } from "../helpers/jsonCol.js";

export function rowToKey(row) { if (!row) return null; return { id:row.id,key:row.key,name:row.name,machineId:row.machineId,isActive:row.isActive===1||row.isActive===true,createdAt:row.createdAt,creditBalance:Number(row.creditBalance)||0,totalTopup:Number(row.totalTopup)||0,totalSpent:Number(row.totalSpent)||0,allowedModels:parseJson(row.allowedModels,[]),allowedCombos:parseJson(row.allowedCombos,[]),notes:row.notes||null,updatedAt:row.updatedAt||row.createdAt }; }
export async function getApiKeys(){const db=await getAdapter();return db.all("SELECT * FROM apiKeys ORDER BY createdAt ASC").map(rowToKey);}
export async function getApiKeyById(id){const db=await getAdapter();return rowToKey(db.get("SELECT * FROM apiKeys WHERE id=?",[id]));}
export async function getApiKeyByValue(key){const db=await getAdapter();return rowToKey(db.get("SELECT * FROM apiKeys WHERE key=?",[key]));}
export async function createApiKey(name,machineId,metadata={}) { if(!machineId)throw new Error("machineId is required"); const db=await getAdapter();const {generateApiKeyWithMachine}=await import("@/shared/utils/apiKey");const now=new Date().toISOString(),result=generateApiKeyWithMachine(machineId);const apiKey={id:uuidv4(),name,key:result.key,machineId,isActive:true,createdAt:now,updatedAt:now,creditBalance:0,totalTopup:0,totalSpent:0,allowedModels:Array.isArray(metadata.allowedModels)?metadata.allowedModels:[],allowedCombos:Array.isArray(metadata.allowedCombos)?metadata.allowedCombos:[],notes:metadata.notes||null};db.run("INSERT INTO apiKeys(id,key,name,machineId,isActive,createdAt,updatedAt,allowedModels,allowedCombos,notes) VALUES(?,?,?,?,?,?,?,?,?,?)",[apiKey.id,apiKey.key,apiKey.name,apiKey.machineId,1,now,now,stringifyJson(apiKey.allowedModels),stringifyJson(apiKey.allowedCombos),apiKey.notes]);return apiKey; }
export async function updateApiKey(id,data){const db=await getAdapter();let result=null;db.transaction(()=>{const current=rowToKey(db.get("SELECT * FROM apiKeys WHERE id=?",[id]));if(!current)return;const allowed=["name","isActive","allowedModels","allowedCombos","notes"];const next={...current};for(const k of allowed)if(Object.hasOwn(data,k))next[k]=data[k];next.updatedAt=new Date().toISOString();db.run("UPDATE apiKeys SET name=?,isActive=?,allowedModels=?,allowedCombos=?,notes=?,updatedAt=? WHERE id=?",[next.name,next.isActive?1:0,stringifyJson(next.allowedModels||[]),stringifyJson(next.allowedCombos||[]),next.notes,next.updatedAt,id]);result=next;});return result;}
export async function deleteApiKey(id){const db=await getAdapter();return (db.run("DELETE FROM apiKeys WHERE id=?",[id])?.changes??0)>0;}
export async function validateApiKey(key){return !!(await getApiKeyByValue(key))?.isActive;}
